export type Pipeline = { id: string; name: string; description: string; tags: string[]; sectors: string[] };
export type Stage = { id: string; name: string; color: string; order_index: number; is_loss: boolean; is_win: boolean };
export type Profile = { id: string; full_name: string; avatar_url: string | null };
export type Task = { 
  id: string; 
  stage_id: string; 
  title: string; 
  description: string; 
  position_index: number; 
  client_id: string | null; 
  value: number | null;
  assigned_to: string | null;
  tags: string[];
  created_at: string;
  motivo_perda?: string;
  phone?: string | null;
  sector?: string | null;
  processo_1grau?: string | null;
  processo_2grau?: string | null;
  demanda?: string | null;
  andamento_1grau?: string | null;
  andamento_2grau?: string | null;
  orgao_julgador?: string | null;
  tutela_urgencia?: string | null;
  sentenca?: string | null;
  reu?: string | null;
  valor_causa?: number | null;
  prazo_fatal?: string | null;
  liminar_deferida?: boolean | null;
  data_ultima_movimentacao?: string;
  client_name?: string | null;
  drive_link?: string | null;
  movimentacoes_timeline?: {
    data?: string | null;
    conteudo?: string | null;
    tipo_evento?: string | null;
    criado_em?: string | null;
    escavador_movimentacao_id?: number | null;
  }[] | null;
};
